---
- name: Initial Proxmox config after installation
  hosts: proxmox
  #become: true

  roles:
    - sources
    - nag_msg
    - high_availability
    - upgrade
    - cpu_microcode
    - create_users
    - reboot
