---
- name: Remove PVE-ENTERPRISE repository
  block:
    - name: Backup ceph.list file
      copy:
        remote_src: true
        src: /etc/apt/sources.list.d/ceph.list
        dest: /etc/apt/sources.list.d/ceph.list_bak
      register: ceph

    - name: Remove ceph.list file
      file:
        path: /etc/apt/sources.list.d/ceph.list
        state: absent
      when: ceph.changed
  ignore_errors: true

- name: Remove CEPH repository
  block:
    - name: Backup pve-enterprise.list file
      copy:
        remote_src: true
        src: /etc/apt/sources.list.d/pve-enterprise.list
        dest: /etc/apt/sources.list.d/pve-enterprise.list_bak
      register: pve_sub

    - name: Remove pve-enterprise.list file
      file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent
      when: pve_sub.changed
  ignore_errors: true

- name: Add PVE-NO-SUBSCRIPTION repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
    state: present
    filename: pve-no-subscription

- name: Add PVETEST repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve bookworm pvetest
    state: present
    filename: pvetest

- name: Add CEPH-QUINCY repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription
    state: present
    filename: ceph-quincy

- name: Add CEPH-REEF repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/ceph-reef bookworm no-subscription
    state: present
    filename: ceph-reef
