---
- name: Disable CEPH repository
  lineinfile:
    dest: /etc/apt/sources.list.d/ceph.list
    regexp: '(?i)^(deb.*)'
    line: '# \1'
    backrefs: yes
    state: present

- name: Disable PVE-ENTERPRISE repository
  lineinfile:
    dest: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '(?i)^(deb.*)'
    line: '# \1'
    backrefs: yes
    state: present

- name: Add PVE-NO-SUBSCRIPTION repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
    state: present
    filename: pve-no-subscription

- name: Add PVETEST repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve bookworm pvetest
    state: present
    filename: pvetest

- name: Add CEPH-QUINCY repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription
    state: present
    filename: ceph-quincy

- name: Add CEPH-REEF repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/ceph-reef bookworm no-subscription
    state: present
    filename: ceph-reef
