---
- name: Enable pve-ha-lrm, pve-ha-crm, and corosync services
  systemd:
    name: '{{ item }}'
    enabled: yes
    state: restarted
  with_items:
    - pve-ha-lrm
    - pve-ha-crm
    - corosync
  when: high_availability == 1

- name: Disable pve-ha-lrm, pve-ha-crm, and corosync services
  systemd:
    name: '{{ item }}'
    enabled: no
    state: restarted
  with_items:
    - pve-ha-lrm
    - pve-ha-crm
    - corosync
  when: high_availability == 0
